FROM nginx:1.25.3-alpine3.18
LABEL MAINTAINER="Madhu Akula" INFO="Kubernetes Goat"

COPY kubernetes-goat.png /usr/share/nginx/html/kubernetes-goat.png
COPY index.html /usr/share/nginx/html/index.html
